version: '3.9'

services:
  backend:
    build:
      context: ./src
      dockerfile: TodoList.API/Dockerfile
    ports:
      - "5206:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoDb=mongodb://admin:password1@mongodb:27017/
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./src
      dockerfile: TodoList.WebUIServer/Dockerfile
    ports:
      - "5030:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BackendUrl=http://backend:8080

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password1